- hosts: all
  become: yes
  vars: 
    packages:
      - apache2
      - tree 
      - unzip
    hello: world
  tasks:
  - name: Install install packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    when: hello == "world"

  - name: Start service apache, if not started
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes

  - name: Add the user Tim
    ansible.builtin.user:
      name: "{{ item }}"
    loop:
      - tim
      - ann
      - brad

  #   ansible.builtin.shell: useradd tim



  
    
     